version: '3.8'

services:
  # Service 1: Your Go Backend
  api:
    build: .
    ports:
      - "5005:5005"
    environment:
      - PORT=5005
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=crosscast_db
      - DB_PORT=5432
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY} # Reads from your local .env file
    depends_on:
      - db

  # Service 2: The Database
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=crosscast_db
    ports:
      - "5433:5432" # Allows you to connect via a GUI tool like TablePlus/DBeaver
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: